local t = require('minitest')
local fakes = require('fakes')
local clientsModule = require('/lua/ge/extensions/beamRemotePlus/clients')

local function setup()
  local input, clock = fakes.input(), fakes.clock()
  return clientsModule.new(input, clock.fn), input, clock
end

t.describe('clients: connection lifecycle', function()
  t.it('creates one virtual device per phone with the right input map', function()
    local reg, input = setup()
    local client, isNew = reg.connect('10.0.0.2', { code = '1', version = 2, deviceName = 'Pixel' })
    t.assertTrue(isNew)
    t.assertEquals(client.deviceName, 'Pixel')
    t.assertEquals(client.version, 2)
    t.assertEquals(input.created[1].product, 'bngremoteplusv1')
    t.assertEquals(input.created[1].name, 'BeamRemotePlus (Pixel)')
    t.assertEquals(input.created[1].axes, 3)
  end)
  t.it('reuses the existing client on repeated pings', function()
    local reg, input = setup()
    reg.connect('a', { version = 1 })
    local _, isNew = reg.connect('a', { version = 1 })
    t.assertFalse(isNew)
    t.assertEquals(#input.created, 1)
    t.assertEquals(reg.count(), 1)
  end)
  t.it('reports a device creation failure', function()
    local reg, input = setup()
    input.failCreate = true
    local client, _, err = reg.connect('a', {})
    t.assertNil(client)
    t.assertEquals(err, 'device_creation_failed')
  end)
  t.it('reports a missing virtual input API', function()
    local _, _, err = clientsModule.new(nil, function() return 0 end).connect('a', {})
    t.assertEquals(err, 'virtual_input_unavailable')
  end)
  t.it('falls back to the IP as device name', function()
    local reg = setup()
    t.assertEquals(reg.connect('1.2.3.4', {}).deviceName, '1.2.3.4')
  end)
end)

t.describe('clients: disconnection', function()
  t.it('deletes the device and releases active holds', function()
    local reg, input = setup()
    local client = reg.connect('a', {})
    client.holds.horn = true
    local released = {}
    reg.disconnect('a', function(_, name) released[#released + 1] = name end)
    t.assertEquals(released[1], 'horn')
    t.assertEquals(input.deleted[1], client.deviceInst)
    t.assertNil(reg.get('a'))
  end)
  t.it('expires silent phones only', function()
    local reg, _, clock = setup()
    reg.connect('old', {})
    clock.advance(9000)
    reg.connect('new', {})
    clock.advance(2000)
    local expired = reg.expire(clock.now, 10000)
    t.assertEquals(#expired, 1)
    t.assertEquals(expired[1].ip, 'old')
    t.assertNotNil(reg.get('new'))
  end)
  t.it('disconnects everybody', function()
    local reg = setup()
    reg.connect('a', {})
    reg.connect('b', {})
    reg.disconnectAll()
    t.assertEquals(reg.count(), 0)
  end)
end)

t.describe('clients: players (local multiplayer)', function()
  t.it('assigns BeamNG players to the matching virtual devices', function()
    local reg = setup()
    local a = reg.connect('a', {})
    local b = reg.connect('b', {})
    local changed = reg.assignPlayers({ ['vinput' .. a.deviceInst] = 0, ['vinput' .. b.deviceInst] = 1, keyboard0 = 0 })
    t.assertEquals(#changed, 2)
    t.assertEquals(a.player, 0)
    t.assertEquals(b.player, 1)
  end)
  t.it('reports only actual changes', function()
    local reg = setup()
    local a = reg.connect('a', {})
    reg.assignPlayers({ ['vinput' .. a.deviceInst] = 0 })
    t.assertEquals(#reg.assignPlayers({ ['vinput' .. a.deviceInst] = 0 }), 0)
  end)
end)

t.describe('clients: control', function()
  t.it('emits every axis on the first packet then only changes', function()
    local reg, input = setup()
    local c = reg.connect('a', {})
    reg.applyControl(c, 0.5, 0.2, 0)
    t.assertEquals(#input.emitted, 3)
    reg.applyControl(c, 0.5, 0.3, 0)
    t.assertEquals(#input.emitted, 4)
    t.assertEquals(input.emitted[4].index, 1)
  end)
  t.it('clamps out-of-range values', function()
    local reg, input = setup()
    local c = reg.connect('a', {})
    reg.applyControl(c, 2, -1, 0 / 0)
    t.assertEquals(input.emitted[1].value, 1)
    t.assertEquals(input.emitted[2].value, 0)
    t.assertEquals(input.emitted[3].value, 0)
  end)
  t.it('pulses a button (press then release)', function()
    local reg, input = setup()
    local c = reg.connect('a', {})
    reg.pulseButton(c, 1)
    t.assertEquals(input.emitted[1].value, 1)
    t.assertEquals(input.emitted[2].value, 0)
    t.assertEquals(input.emitted[2].kind, 'button')
  end)
end)
