local t = require('minitest')
local fakes = require('fakes')
local commandsModule = require('/lua/ge/extensions/beamRemotePlus/commands')

local function setup(opts)
  opts = opts or {}
  local vehicle = fakes.vehicle(7)
  local calls = {}
  local commands = commandsModule.new({
    getVehicle = function(player) calls.player = player return not opts.noVehicle and vehicle or nil end,
    switchVehicle = function(player, dir) calls.switch = dir return true end,
    cycleCamera = function(player, offset) calls.camera = offset return true end,
    pulseButton = function(_, button) calls.button = button end,
    buttons = { shiftUp = 0, shiftDown = 1 },
  })
  local client = { player = 1, holds = {}, debug = false }
  return commands, client, vehicle, calls
end

t.describe('commands: hold actions', function()
  t.it('horn on/off runs the native horn code on the player vehicle', function()
    local commands, client, vehicle, calls = setup()
    t.assertTrue(commands.execute(client, 'horn', '1'))
    t.assertContains(vehicle.commands[1], 'electrics.horn(true)')
    t.assertTrue(client.holds.horn)
    t.assertEquals(calls.player, 1)
    t.assertTrue(commands.execute(client, 'horn', '0'))
    t.assertContains(vehicle.commands[2], 'electrics.horn(false)')
    t.assertNil(client.holds.horn)
  end)
  t.it('high beams stay on while held (native flash action)', function()
    local commands, client, vehicle = setup()
    commands.execute(client, 'highbeam', '1')
    t.assertContains(vehicle.commands[1], 'light_flash_highbeams(true)')
  end)
  t.it('rejects a hold without on/off argument', function()
    local commands, client = setup()
    local ok, err = commands.execute(client, 'horn')
    t.assertFalse(ok)
    t.assertEquals(err, commandsModule.ERR_BAD_ARGUMENT)
  end)
  t.it('release() turns a hold off', function()
    local commands, client, vehicle = setup()
    commands.release(client, 'horn')
    t.assertContains(vehicle.commands[1], 'electrics.horn(false)')
  end)
  t.it('keeps protocol v1 recover names working', function()
    local commands, client, vehicle = setup()
    local ok, _, name = commands.execute(client, 'recover_start')
    t.assertTrue(ok)
    t.assertEquals(name, 'recover')
    t.assertContains(vehicle.commands[1], 'startRecovering')
  end)
end)

t.describe('commands: press actions', function()
  t.it('skeleton asks the vehicle VM for its geometry', function()
    local commands, client, vehicle = setup()
    t.assertTrue(commands.execute(client, 'skeleton'))
    t.assertContains(vehicle.commands[1], 'sendSkeleton()')
    t.assertTrue(commandsModule.DISPLAY_COMMANDS.skeleton)
  end)
  t.it('hazard toggles the warning signal', function()
    local commands, client, vehicle = setup()
    t.assertTrue(commands.execute(client, 'hazard'))
    t.assertContains(vehicle.commands[1], 'toggle_warn_signal')
  end)
  t.it('fails with no_vehicle when the player has no vehicle', function()
    local commands, client = setup({ noVehicle = true })
    local ok, err = commands.execute(client, 'lights')
    t.assertFalse(ok)
    t.assertEquals(err, commandsModule.ERR_NO_VEHICLE)
  end)
  t.it('wraps vehicle code in a pcall', function()
    t.assertContains(commandsModule.wrapVehicleCode('x()'), 'pcall(function() x() end)')
  end)
  t.it('player 0 is used before BeamNG assigned one', function()
    local commands, client, _, calls = setup()
    client.player = nil
    commands.execute(client, 'hazard')
    t.assertEquals(calls.player, 0)
  end)
end)

t.describe('commands: special', function()
  t.it('switches vehicle and forces a full axis re-emit', function()
    local commands, client, _, calls = setup()
    commands.execute(client, 'prev_vehicle')
    t.assertEquals(calls.switch, -1)
    t.assertTrue(client.forceEmit)
  end)
  t.it('cycles the camera', function()
    local commands, client, _, calls = setup()
    commands.execute(client, 'cam_next')
    t.assertEquals(calls.camera, 1)
  end)
  t.it('shifts with the virtual buttons', function()
    local commands, client, _, calls = setup()
    commands.execute(client, 'gear_down')
    t.assertEquals(calls.button, 1)
  end)
  t.it('toggles per-client debug acks', function()
    local commands, client = setup()
    commands.execute(client, 'debug', '1')
    t.assertTrue(client.debug)
  end)
  t.it('reports unknown commands', function()
    local commands, client = setup()
    local ok, err = commands.execute(client, 'fly')
    t.assertFalse(ok)
    t.assertEquals(err, commandsModule.ERR_UNKNOWN)
  end)
  t.it('lists every command name once, sorted', function()
    local commands = setup()
    local names = commands.names()
    for i = 2, #names do t.assertTrue(names[i - 1] < names[i]) end
    t.assertTrue(#names > 20)
  end)
end)
