local t = require('minitest')
local fakes = require('fakes')
local config = require('/lua/ge/extensions/beamRemotePlus/config')

t.describe('config', function()
  t.it('is enabled by default (no file yet)', function()
    local c = config.new(fakes.memoryFiles())
    c.load()
    t.assertTrue(c.get('enabled'))
    t.assertFalse(c.get('debug'))
  end)
  t.it('loads saved values', function()
    local c = config.new(fakes.memoryFiles({ [config.FILE_PATH] = { enabled = false, debug = true } }))
    c.load()
    t.assertFalse(c.get('enabled'))
    t.assertTrue(c.get('debug'))
  end)
  t.it('ignores unknown keys and wrong types', function()
    local values = config.sanitize({ enabled = 'no', hacker = 1 })
    t.assertTrue(values.enabled)
    t.assertNil(values.hacker)
  end)
  t.it('survives a reader that throws', function()
    local c = config.new({ readJson = function() error('corrupt') end, writeJson = function() end })
    t.assertTrue(c.load().enabled)
  end)
  t.it('persists valid changes only', function()
    local files = fakes.memoryFiles()
    local c = config.new(files)
    t.assertTrue(c.set('enabled', false))
    t.assertFalse(files.files[config.FILE_PATH].enabled)
    t.assertFalse(c.set('enabled', 'off'))
    t.assertFalse(c.set('unknown', true))
  end)
end)
