local t = require('minitest')
local json = require('/lua/ge/extensions/beamRemotePlus/json')

t.describe('json.encode', function()
  t.it('encodes scalars', function()
    t.assertEquals(json.encode(nil), 'null')
    t.assertEquals(json.encode(true), 'true')
    t.assertEquals(json.encode(42), '42')
    t.assertEquals(json.encode(-1.5), '-1.5')
    t.assertEquals(json.encode(0.125), '0.125')
  end)
  t.it('turns NaN and infinities into null (always valid JSON)', function()
    t.assertEquals(json.encode(0 / 0), 'null')
    t.assertEquals(json.encode(math.huge), 'null')
  end)
  t.it('escapes strings', function()
    t.assertEquals(json.encode('a"b\\c\n'), '"a\\"b\\\\c\\n"')
    t.assertEquals(json.encode('\1'), '"\\u0001"')
  end)
  t.it('encodes arrays and objects with sorted keys', function()
    t.assertEquals(json.encode({ 1, 2, 3 }), '[1,2,3]')
    t.assertEquals(json.encode({ b = 1, a = { c = false } }), '{"a":{"c":false},"b":1}')
  end)
  t.it('encodes an empty table as an object', function()
    t.assertEquals(json.encode({}), '{}')
  end)
  t.it('refuses functions', function()
    t.assertFalse(pcall(json.encode, print))
  end)
end)

t.describe('json.encode arrays', function()
  t.it('encodes a table marked as array as [] when empty', function()
    t.assertEquals(json.encode(setmetatable({}, { __jsonArray = true })), '[]')
  end)
end)
