local t = require('minitest')
local protocol = require('/lua/ge/extensions/beamRemotePlus/protocol')
local ffi = require('ffi')

t.describe('protocol: discover / hello', function()
  t.it('recognises only the exact discover message', function()
    t.assertTrue(protocol.isDiscoverMessage('beamngremoteplus|discover'))
    t.assertFalse(protocol.isDiscoverMessage('beamngremoteplus|discover|'))
    t.assertFalse(protocol.isDiscoverMessage(nil))
  end)
  t.it('builds a hello with code and label', function()
    t.assertEquals(protocol.buildHelloMessage(20367, "Loka's PC"), "beamngremoteplus|hello|20367|Loka's PC")
  end)
  t.it('uses a default label and strips field separators', function()
    t.assertEquals(protocol.buildHelloMessage('1'), 'beamngremoteplus|hello|1|BeamNG.drive')
    t.assertEquals(protocol.buildHelloMessage('1', 'a|b'), 'beamngremoteplus|hello|1|a b')
  end)
end)

t.describe('protocol: ping / pong', function()
  t.it('parses a v1 ping (code only) as protocol 1', function()
    local ping = protocol.parsePing('beamngremoteplus|ping|20367')
    t.assertEquals(ping.code, '20367')
    t.assertEquals(ping.version, 1)
    t.assertNil(ping.deviceName)
  end)
  t.it('parses a v2 ping with version and device name', function()
    local ping = protocol.parsePing('beamngremoteplus|ping|20367|2|Pixel 8')
    t.assertEquals(ping.version, 2)
    t.assertEquals(ping.deviceName, 'Pixel 8')
  end)
  t.it('rejects a ping without code', function()
    t.assertNil(protocol.parsePing('beamngremoteplus|ping|'))
    t.assertNil(protocol.parsePing('beamng|20367'))
  end)
  t.it('round-trips buildPingMessage / parsePing', function()
    local ping = protocol.parsePing(protocol.buildPingMessage(42, 2, 'a|b'))
    t.assertEquals(ping.code, '42')
    t.assertEquals(ping.deviceName, 'a b')
  end)
  t.it('matches the pairing code', function()
    t.assertTrue(protocol.pingMatchesCode('beamngremoteplus|ping|20367|2|x', '20367'))
    t.assertFalse(protocol.pingMatchesCode('beamngremoteplus|ping|99999', '20367'))
    t.assertFalse(protocol.pingMatchesCode('beamngremoteplus|ping|20367', nil))
  end)
  t.it('negotiates the lowest common version', function()
    t.assertEquals(protocol.negotiateVersion(1), 1)
    t.assertEquals(protocol.negotiateVersion(2), 2)
    t.assertEquals(protocol.negotiateVersion(99), protocol.PROTOCOL_VERSION)
    t.assertEquals(protocol.negotiateVersion(nil), 1)
  end)
  t.it('builds a pong carrying the negotiated version', function()
    t.assertEquals(protocol.buildPongMessage('20367', 1), 'beamngremoteplus|pong|20367|1')
    t.assertEquals(protocol.buildPongMessage('20367'), 'beamngremoteplus|pong|20367|2')
  end)
end)

t.describe('protocol: commands', function()
  t.it('parses a command without argument', function()
    local name, arg = protocol.parseCommand('cmd|next_vehicle')
    t.assertEquals(name, 'next_vehicle')
    t.assertNil(arg)
  end)
  t.it('parses a command with argument', function()
    local name, arg = protocol.parseCommand('cmd|horn|1')
    t.assertEquals(name, 'horn')
    t.assertEquals(arg, '1')
  end)
  t.it('rejects non commands and empty names', function()
    t.assertNil(protocol.parseCommand('beamngremoteplus|ping|1'))
    t.assertNil(protocol.parseCommand('cmd|'))
  end)
  t.it('builds commands', function()
    t.assertEquals(protocol.buildCommand('horn', 1), 'cmd|horn|1')
    t.assertEquals(protocol.buildCommand('hazard'), 'cmd|hazard')
  end)
  t.it('a binary control packet can never look like a command', function()
    t.assertFalse(protocol.isCmdMessage(protocol.encodeControlPacket(1, 1, 1)))
  end)
end)

t.describe('protocol: control packet', function()
  t.it('round-trips encode / decode', function()
    local s, th, b = protocol.decodeControlPacket(protocol.encodeControlPacket(0.25, 0.5, 0.75))
    t.assertCloseTo(s, 0.25)
    t.assertCloseTo(th, 0.5)
    t.assertCloseTo(b, 0.75)
  end)
  t.it('rejects a packet of the wrong size', function()
    t.assertNil(protocol.decodeControlPacket('abc'))
    t.assertNil(protocol.decodeControlPacket(nil))
  end)
  t.it('is little-endian like the Dart side', function()
    local bytes = protocol.encodeControlPacket(1, 0, 0)
    t.assertEquals(bytes:byte(4), 0x3F)
    t.assertEquals(bytes:byte(3), 0x80)
  end)
  t.it('clamps values and neutralises NaN', function()
    t.assertEquals(protocol.clampUnit(-1), 0)
    t.assertEquals(protocol.clampUnit(2), 1)
    t.assertEquals(protocol.clampUnit(0 / 0), 0)
    t.assertEquals(protocol.clampUnit('x'), 0)
  end)
end)

t.describe('protocol: legacy v1 telemetry', function()
  local function decode(bytes)
    local p = ffi.new('rp_telemetry_v2_t')
    ffi.copy(p, bytes, 36)
    return p
  end
  t.it('encodes 36 bytes', function()
    t.assertEquals(#protocol.encodeLegacyTelemetry({}), 36)
  end)
  t.it('maps the normalized telemetry to the v1 layout', function()
    local p = decode(protocol.encodeLegacyTelemetry({
      speed = 10, rpm = 3000, maxRpm = 7000, gearIndex = 2, fuel = 0.5,
      waterTemp = 90, oilTemp = 100, shiftLight = true, lowBeam = true, tcsActive = true,
    }))
    t.assertCloseTo(p.speed, 10)
    t.assertCloseTo(p.redlineRpm, 7000)
    t.assertCloseTo(p.gear, 3)
    t.assertCloseTo(p.engineTemp, 90)
    t.assertCloseTo(p.shiftLight, 1)
    t.assertCloseTo(p.lights, 1 + 128)
    t.assertCloseTo(p.oilTemp, 100)
  end)
  t.it('neutral is the default gear when the index is missing', function()
    t.assertCloseTo(decode(protocol.encodeLegacyTelemetry({})).gear, 0)
    t.assertEquals(protocol.gearFromIndex(0), 1)
    t.assertEquals(protocol.gearFromIndex(-1), 0)
  end)
  t.it('never fails on non-numeric values', function()
    t.assertCloseTo(decode(protocol.encodeLegacyTelemetry({ speed = 'x', rpm = 0 / 0 })).speed, 0)
  end)
  t.it('computes the lights bitmask', function()
    t.assertEquals(protocol.computeLightsBitmask({}), 0)
    t.assertEquals(protocol.computeLightsBitmask({ highBeam = true, signalLeft = true, absActive = true }), 2 + 8 + 64)
  end)
end)

t.describe('protocol: v2 JSON messages', function()
  t.it('tags telemetry with its type', function()
    t.assertEquals(protocol.buildTelemetryMessage({ rpm = 1000 }), '{"rpm":1000,"type":"telemetry"}')
  end)
  t.it('builds acks with and without error', function()
    t.assertEquals(protocol.buildAckMessage('horn|1', true), '{"cmd":"horn|1","ok":true,"type":"ack"}')
    t.assertEquals(protocol.buildAckMessage('x', false, 'unknown_command'),
      '{"cmd":"x","error":"unknown_command","ok":false,"type":"ack"}')
  end)
  t.it('builds session messages', function()
    t.assertEquals(protocol.buildSessionMessage({ player = 1 }), '{"player":1,"type":"session"}')
  end)
end)

t.describe('protocol: timeouts', function()
  t.it('is not expired right after being seen', function()
    t.assertFalse(protocol.isClientTimedOut(1000, 900, 10000))
  end)
  t.it('expires after the timeout and treats nil as never seen', function()
    t.assertTrue(protocol.isClientTimedOut(20001, 10000, 10000))
    t.assertTrue(protocol.isClientTimedOut(20000, nil, 10000))
  end)
end)

t.describe('protocol: second-screen role', function()
  t.it('parses the display role and defaults to controller', function()
    t.assertEquals(protocol.parsePing('beamngremoteplus|ping|1|2|Tab|display').role, protocol.ROLE_DISPLAY)
    t.assertEquals(protocol.parsePing('beamngremoteplus|ping|1|2|Tab').role, protocol.ROLE_CONTROLLER)
    t.assertEquals(protocol.parsePing('beamngremoteplus|ping|1|2|Tab|weird').role, protocol.ROLE_CONTROLLER)
  end)
  t.it('round-trips the role', function()
    t.assertEquals(protocol.parsePing(protocol.buildPingMessage(1, 2, 'Tab', 'display')).role, 'display')
  end)
end)

t.describe('protocol: vehicle skeleton', function()
  local s = { id = '3-ab', segments = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 }, wheels = { FL = { -80, 150, 31, 22 } }, engine = { 0, 120 } }
  t.it('splits the segments into standalone datagrams', function()
    local messages = protocol.buildSkeletonMessages(s, 2)
    t.assertEquals(#messages, 2)
    t.assertContains(messages[1], '"type":"skeleton"')
    t.assertContains(messages[1], '"offset":0')
    t.assertContains(messages[1], '"count":3')
    t.assertContains(messages[1], '"seg":[1,2,3,4,5,6,7,8]')
    t.assertContains(messages[2], '"offset":2')
    t.assertContains(messages[2], '"seg":[9,10,11,12]')
    t.assertContains(messages[2], '"wheels":{"FL":[-80,150,31,22]}')
    t.assertContains(messages[2], '"engine":[0,120]')
  end)
  t.it('one datagram stays a few kilobytes', function()
    local big = { id = 'x', segments = {} }
    for i = 1, 4000 * 4 do big.segments[i] = -1234 end
    local messages = protocol.buildSkeletonMessages(big)
    t.assertEquals(#messages, math.ceil(4000 / protocol.SKELETON_SEGMENTS_PER_MESSAGE))
    t.assertTrue(#messages[1] < 4096)
  end)
  t.it('nothing for a malformed skeleton', function()
    t.assertEquals(#protocol.buildSkeletonMessages(nil), 0)
    t.assertEquals(#protocol.buildSkeletonMessages({ segments = {} }), 0)
  end)
end)
