local t = require('minitest')
local testDir = arg[0]:match('(.*/)') or './'
local vehicleTelemetry = dofile(testDir .. '../src/lua/vehicle/extensions/beamRemotePlus/telemetry.lua')

t.describe('vehicle telemetry collect()', function()
  t.it('maps electrics to the normalized names', function()
    local s = vehicleTelemetry.collect({
      wheelspeed = 27.777, rpm = 6543.4, maxrpm = 8000, gear = 'S5', gearIndex = 5,
      fuel = 0.51234, watertemp = 92.26, oiltemp = 101, turboBoost = 1.234,
      lowbeam = 1, highbeam = 0, signal_L = 1, hazard_enabled = 0, parkingbrake = 0.4,
      hasABS = 1, absActive = 0, escActive = 1, esc = 0, tcsActive = 0,
      engineRunning = 1, ignitionLevel = 2, odometer = 123456.7,
    }, { gx = 0.12345, envTemp = 21.37 })
    t.assertCloseTo(s.speed, 27.78)
    t.assertEquals(s.rpm, 6543)
    t.assertEquals(s.gear, 'S5')
    t.assertCloseTo(s.fuel, 0.5123)
    t.assertCloseTo(s.waterTemp, 92.3)
    t.assertTrue(s.lowBeam)
    t.assertFalse(s.highBeam)
    t.assertTrue(s.signalLeft)
    t.assertFalse(s.hazard)
    t.assertTrue(s.parkingBrake)
    t.assertTrue(s.hasAbs)
    t.assertTrue(s.hasEsc)
    t.assertTrue(s.escActive)
    t.assertTrue(s.engineRunning)
    t.assertCloseTo(s.gx, 0.123)
    t.assertCloseTo(s.envTemp, 21.4)
  end)
  t.it('labels numeric gears of manual gearboxes like the car does', function()
    t.assertEquals(vehicleTelemetry.gearLabel(0), 'N')
    t.assertEquals(vehicleTelemetry.gearLabel(-1), 'R')
    t.assertEquals(vehicleTelemetry.gearLabel(3), '3')
    t.assertEquals(vehicleTelemetry.gearLabel('D'), 'D')
    t.assertNil(vehicleTelemetry.gearLabel(nil))
  end)
  t.it('omits what the vehicle does not provide', function()
    local s = vehicleTelemetry.collect({ rpm = 1000 })
    t.assertNil(s.oilTemp)
    t.assertNil(s.hasAbs)
    t.assertNil(s.parkingBrake)
    t.assertNil(s.lowPressure)
  end)
  t.it('drops non-finite values', function()
    local s = vehicleTelemetry.collect({ rpm = 0 / 0, wheelspeed = math.huge })
    t.assertNil(s.rpm)
    t.assertNil(s.speed)
  end)
  t.it('uses the vehicle shift light when present', function()
    t.assertTrue(vehicleTelemetry.collect({ shouldShift = true, rpm = 10, maxrpm = 8000 }).shiftLight)
  end)
  t.it('computes a shift light at 95% of max rpm except on top gear', function()
    t.assertTrue(vehicleTelemetry.collect({ rpm = 7700, maxrpm = 8000, gearIndex = 3, maxGearIndex = 6 }).shiftLight)
    t.assertFalse(vehicleTelemetry.collect({ rpm = 7000, maxrpm = 8000 }).shiftLight)
    t.assertFalse(vehicleTelemetry.collect({ rpm = 7900, maxrpm = 8000, gearIndex = 6, maxGearIndex = 6 }).shiftLight)
  end)
  t.it('reads the configured tyre pressures (kPa) per wheel', function()
    local triangles = {
      { pressureGroup = 'wheel_FL', pressurePSI = 20 },
      { pressureGroup = 'wheel_FL', pressurePSI = 20 },
      { pressureGroup = 'wheel_RR', pressurePSI = 30 },
      { id1 = 1 }, -- not pressured
    }
    local n = vehicleTelemetry.nominalPressures(triangles, { FL = 'wheel_FL', RR = 'wheel_RR', RL = 'missing' })
    t.assertCloseTo(n.FL, 137.9)
    t.assertCloseTo(n.RR, 206.8)
    t.assertNil(n.RL)
    t.assertNil(vehicleTelemetry.nominalPressures({}, { FL = 'wheel_FL' }))
  end)
  t.it('reads the brake disc temperatures', function()
    local s = vehicleTelemetry.collect({ wheelThermals = { FL = { brakeSurfaceTemperature = 351.6 }, RR = {} } })
    t.assertEquals(s.brakeTemps.FL, 352)
    t.assertNil(s.brakeTemps.RR)
    t.assertNil(vehicleTelemetry.collect({}).brakeTemps)
  end)
  t.it('reports low oil pressure from either electric', function()
    t.assertTrue(vehicleTelemetry.collect({ lowpressure = 0, oil = 1 }).lowPressure)
    t.assertFalse(vehicleTelemetry.collect({ lowpressure = 0 }).lowPressure)
  end)
end)
